### ISSUE TITLE
Image 첨부파일 폴더

### ISSUE THREAD

**Issue by dhfpswlqkd** [Yeon-ksy/CV23-TIL#3]
## description
Image 첨부할 때 이미지 저장 폴더 따로 둡시다!

## Todo
- [x] 업로드된 이미지 옮기기

## ETC
그냥 이슈 써보고 싶었어요...

**Comment by Yeon-ksy** [comment]
이미지 저장한 거 저인데 이미지 없어도 되도록 수정했습니다. 제 branch에 없앴는데 아직, main으로 병합을 안해서 남아있는 거 같네요. 다른 분들 위해서 이미지 저장 폴더 만들어도 괜찮을 것 같습니다
